"""initial schema

Revision ID: f619e20d14c1
Revises: 
Create Date: 2026-03-09 03:54:03.980375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f619e20d14c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('team', 'player', 'league', name='entity_type'), nullable=False),
    sa.Column('canonical_id', sa.String(length=36), nullable=False),
    sa.Column('alias_name', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'alias_name', 'source', name='uq_alias')
    )
    op.create_table('bankroll_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('balance_dkk', sa.Float(), nullable=False),
    sa.Column('peak_dkk', sa.Float(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('daily_exposure_pct', sa.Float(), nullable=False),
    sa.Column('total_bets', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_resolution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('input_name', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('resolved_to_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_to_name', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('optic_odds_id', sa.String(length=100), nullable=True),
    sa.Column('the_odds_api_key', sa.String(length=100), nullable=True),
    sa.Column('sportmonks_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('training_data_cutoff', sa.Date(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=False),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_fixtures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('optic_odds', 'the_odds_api', 'sportmonks', name='data_source'), nullable=False),
    sa.Column('source_fixture_id', sa.String(length=100), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_odds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('optic_odds', 'the_odds_api', 'sportmonks', name='data_source'), nullable=False),
    sa.Column('source_fixture_id', sa.String(length=100), nullable=False),
    sa.Column('source_market', sa.String(length=100), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_player_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('optic_odds', 'the_odds_api', 'sportmonks', name='data_source'), nullable=False),
    sa.Column('source_fixture_id', sa.String(length=100), nullable=False),
    sa.Column('source_player_id', sa.String(length=100), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=True),
    sa.Column('optic_odds_id', sa.String(length=100), nullable=True),
    sa.Column('the_odds_api_name', sa.String(length=200), nullable=True),
    sa.Column('sportmonks_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', 'postponed', 'cancelled', name='match_status'), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('optic_odds_fixture_id', sa.String(length=100), nullable=True),
    sa.Column('the_odds_api_event_id', sa.String(length=100), nullable=True),
    sa.Column('sportmonks_fixture_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('optic_odds_id', sa.String(length=100), nullable=True),
    sa.Column('sportmonks_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ev_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('odds_at_signal', sa.Float(), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('ev_pct', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_stake_pct', sa.Float(), nullable=False),
    sa.Column('suggested_stake_dkk', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='signal_status'), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reasoning', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_vectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('team', 'player', name='feature_entity_type'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('corners', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('possession_pct', sa.Float(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('pass_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('predicted_prob', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_outcome', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('opening_odds', sa.Float(), nullable=False),
    sa.Column('closing_odds', sa.Float(), nullable=False),
    sa.Column('movement_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('optic_odds', 'the_odds_api', 'sportmonks', name='data_source'), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_match_book_market', 'odds_snapshots', ['match_id', 'bookmaker', 'market', 'selection'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('key_passes', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('pass_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('clearances', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=False),
    sa.Column('dribbles_succeeded', sa.Integer(), nullable=False),
    sa.Column('fouls_committed', sa.Integer(), nullable=False),
    sa.Column('fouls_drawn', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('corners_taken', sa.Integer(), nullable=False),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('stake_dkk', sa.Float(), nullable=False),
    sa.Column('potential_return_dkk', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Enum('pending', 'won', 'lost', 'void', 'half_won', 'half_lost', name='bet_outcome'), nullable=True),
    sa.Column('pnl_dkk', sa.Float(), nullable=True),
    sa.Column('closing_odds', sa.Float(), nullable=True),
    sa.Column('clv_pct', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['ev_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('player_match_stats')
    op.drop_index('ix_odds_match_book_market', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('odds_movements')
    op.drop_table('model_predictions')
    op.drop_table('match_stats')
    op.drop_table('feature_vectors')
    op.drop_table('ev_signals')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('raw_player_stats')
    op.drop_table('raw_odds')
    op.drop_table('raw_fixtures')
    op.drop_table('model_runs')
    op.drop_table('leagues')
    op.drop_table('ingestion_logs')
    op.drop_table('entity_resolution_logs')
    op.drop_table('bankroll_snapshots')
    op.drop_table('aliases')
    # ### end Alembic commands ###
